export const FAVPET_ADD_REQUEST = 'FAVPET_ADD_REQUEST'
export const FAVPET_ADD_SUCCESS = 'FAVPET_ADD_SUCCESS'
export const FAVPET_ADD_FAIL = 'FAVPET_ADD_FAIL'
export const FAVPET_ADD_RESET = 'FAVPET_ADD_RESET'

export const FAVPET_DELETE_REQUEST = 'FAVPET_DELETE_REQUEST'
export const FAVPET_DELETE_SUCCESS = 'FAVPET_DELETE_SUCCESS'
export const FAVPET_DELETE_FAIL = 'FAVPET_DELETE_FAIL'

export const FAVPET_LIST_REQUEST = 'FAVPET_LIST_REQUEST'
export const FAVPET_LIST_SUCCESS = 'FAVPET_LIST_SUCCESS'
export const FAVPET_LIST_FAIL = 'FAVPET_LIST_FAIL'
