export const PETNOTE_ADD_REQUEST = 'PETNOTE_ADD_REQUEST'
export const PETNOTE_ADD_SUCCESS = 'PETNOTE_ADD_SUCCESS'
export const PETNOTE_ADD_FAIL = 'PETNOTE_ADD_FAIL'
export const PETNOTE_ADD_RESET = 'PETNOTE_ADD_RESET'

export const PETNOTE_DELETE_REQUEST = 'PETNOTE_DELETE_REQUEST'
export const PETNOTE_DELETE_SUCCESS = 'PETNOTE_DELETE_SUCCESS'
export const PETNOTE_DELETE_FAIL = 'PETNOTE_DELETE_FAIL'
export const PETNOTE_DELETE_RESET = 'PETNOTE_DELETE_RESET'

export const PETNOTE_LIST_REQUEST = 'PETNOTE_LIST_REQUEST'
export const PETNOTE_LIST_SUCCESS = 'PETNOTE_LIST_SUCCESS'
export const PETNOTE_LIST_FAIL = 'PETNOTE_LIST_FAIL'
